---
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.9.2"
    hooks:
      - id: ruff
        files: "code\/|notebooks\/"
        exclude: "archive\/"
      - id: ruff-format
        files: "code\/|notebooks\/"
        exclude: "archive\/"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-toml
        files: "."
  - repo: https://github.com/srstevenson/nb-clean
    rev: 4.0.1
    hooks:
      - id: nb-clean

ci:
  autofix_prs: false
  autoupdate_schedule: quarterly
