[project]
authors = ["Kryndlea <kryndlea@natur.cuni.cz>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "people_places_germany"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
geopandas = ">=1.0.1,<2"
lonboard = ">=0.10.3,<0.11"
libpysal = ">=4.12.1,<5"
numpy = ">=2.0.2,<3"
pandas = ">=2.2.3,<3"
matplotlib = ">=3.9.3,<4"
jupyterlab = ">=4.3.2,<5"
glasbey = ">=0.2.1,<0.3"
sidecar = ">=0.7.0,<0.8"
pyarrow = ">=18.1.0,<19"
palettable = ">=3.3.3,<4"
